### ISSUE TITLE
Review 💪🏻

### ISSUE THREAD

**Issue by htmlena** [xteryna/zivotopis#1]
Ahoj Teri,

skvělá práce, moc chválím! Vidím, že stránka je responzivní a struktura projektu jasná, líbí se mi, že jsi dala obrázky do složky zvlášť, takže v tom projektu je vetší pořádek. A super, že commity mají smysluplné popisky a že jsi commitovala průběžně 💪 

Správně používáš heading tagy (jedna `h1` na celou stránku, a pak další tagy v dobrým pořádí), máš alt text u obrázku, a plus za to, že jsi použila nejenom `div`y, ale i `section` tam, kde se to hodilo. Keep it up! 🔥 

Co bych doporučila od sebe - pojmenovávat proměnné a třídy anglicky, a commity psát taky v angličtině, je to zvykem všude, i v čistě českých firmách. Angličtina je prostě jazyk komunity programátorů.

Pro styling - využívat primárně třídy místo elementů. Samozřejmě když je stránka menší, tak to ničemu nevadí, ale jakmile se stránka začne rozrůstat a rozhodneš se přidat například další obrázek, kterému budeš chtít dát `width` jen 50%, tak to může udělat neplechu. Můžeme se o tom víc pobavit v úterý. 

Koukám, že v css používáš floaty. Ja bych se tomu osobně vyhnula, už je to takový frontendový přežitek, hehe, ten flexbox je šikovnější na pozicování elementů na stránce, tak si s tím ještě může pohrat kdybys měla volné chvíle. Tady je dobrá [hra](https://flexboxfroggy.com/) na procvíčení :)

**Comment by xteryna** [comment]
Ahoj,
díky za tipy. 
1) s AJ nebude problém, i za sebe cítím, že to i pro mne asi bude lepší anglicky. Hlavně si chci dodělat CV i v AJ, takže si pak časem ty třídy předělám
2) rozumím, pro příště v CSS víc použít třídy
3) popravdě flexbox jsem dosud neznala, HTML/CSS kurz jsem absolvovala na VŠ před 20 lety a to nic takového neexistovalo. A tady v kurzu jsme je ještě neobjevili. Vygooglila jsem je, protože jsem potřebovala dva stejně vysoké sloupce a nedařilo se mi to pořešit. Mrknu na tu hru, moc rada se o nich dozvím víc.

**Comment by htmlena** [comment]
a jinak jsem jeste koukala, ze vlastne floaty vysvetluje Ludek ve videich, a je to asi proto, ze zatim jsme se nedostaly ke flexboxu, takze to pouziti nicemu nevadi :) spis koment do budoucna

**Comment by xteryna** [comment]
Však nevadí, aspoň vím pro příště. A ta hra je moc fajn, budu ráda za podobné tipy.
